### ISSUE TITLE
Mark missing attachments in messages

### ISSUE THREAD

**Issue by Erdodif** [hypergonial/chat#24]
When a missing attachment's link is followed, this XML is omitted by the server:

```xml
<Error>
<script/>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>185158548639059969/185163444524290049/0/image.png</Key>
<BucketName>attachments</BucketName>
<Resource>/attachments/185158548639059969/185163444524290049/0/image.png</Resource>
<RequestId>17D2DE26BA4E8253</RequestId>
<HostId>e0c385c033c4356721cc9121d3109c9b9bfdefb22fd2747078acd22328799e36</HostId>
</Error>
```

Some form of indication is needed so the unreachable files are disabled for the user...

> Repro: when the attachments' bucket is not available or doesn't exist, the server will still save the message with the path to the attachment which will be unreachable...

**Comment by hypergonial** [comment]
This should be fixed now.
