### ISSUE TITLE
Channel memberlist

### ISSUE THREAD

**Issue by Erdodif** [hypergonial/chat#5]
## Basic idea

Each channel should have their own member list, and members should only see the available channels

## Depends on

- #3 
  - For having moderators and privilage levels
- #2 
  - For allowing the user to hide channel and set notification level 
- #4 
  - Channel invitation be possible by mentioning users in it 

## Possible approach

- Channel visibility can be changed by moderators
- Members can be invited by those who are in the same channel 
  -(if channel invitation is allowed 
- Mentioning the specific guild member in the channel may  cause them the be included

**Comment by hypergonial** [comment]
This should be handled by a permissions system instead
