### ISSUE TITLE
Image upload for users and guilds

### ISSUE THREAD

**Issue by Erdodif** [hypergonial/chat#7]
## Basic idea

Image thumbnail to 

## Depends on

- #6 
  - For accepting and providing images on demand 
- #3 
  - For guild image upload
 
## Possible approach

Optional parameter, sending empty payload if image is not set, (allowing frontend to handle blank image templates)

**Comment by hypergonial** [comment]
Uploading images should not be handled differently backend-wise compared to other attachment types.
