### ISSUE TITLE
Download link for large files

### ISSUE THREAD

**Issue by Erdodif** [hypergonial/chat#9]
## Basic idea

Creating download links, when the user sends an attachment after a certain size

## Depends on

- #6  
- #8 
- #1 
  - Download links may share access level and code generating methods with the invitation link system
- #2 
  - The user may choose if they prefer smaller attachments to have links as well 

## Possible approach

- Download links should be authenticated, even if the guild is public
- Download links shall be Guild / Channel specific (channel specific only if the channel is set to private)
- Attachments link can be sent to different guilds, creating new download link to the asset

**Comment by hypergonial** [comment]
This is fundamental to how attachments should work, there is no need to have a seperate issue on this.
